version: '3'
services:
  mongo:
    image: mongo:4.4.4
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_LOGIN
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - ./mongo-data-4.4:/data/db
    command: --wiredTigerCacheSizeGB 1.5

  top-api:
    image: docker.pkg.github.com/yatolstoy/nestjs-course/nest-course:latest
    container_name: top-api
    restart: always
    depends_on:
      - "mongo"
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env
